### ISSUE TITLE
pushNotificationClicked event on android

### ISSUE THREAD

**Issue by OmgDef** [mindbox-cloud/react-native-sdk#15]
On an app launch, the ```pushNotificationClicked``` event can be fired before any listeners are attached on the JS side. So there is no guarantee that callback passed to ```MindboxSdk.onPushClickReceived``` will be called. I think should be implemented the event cache which works similar to iOS ```startObserving``` method and sends the ```pushNotificationClicked``` event only after any listener is attached

**Comment by sergeysozinov** [comment]
Sorry, forgot to write in this ticket after solving the problem. The issue was resolved on March 18, 2022 in version [1.02](https://github.com/mindbox-cloud/react-native-sdk/releases/tag/v1.0.2).

Thank you.
