### ISSUE TITLE
Передача SecretKey

### ISSUE THREAD

**Issue by victorzimnikov** [mindbox-cloud/react-native-sdk#16]
Здравствуйте! Подскажите, пожалуйста, как передавать secretKey? Ни при инициализации, ни при выполнении операции не нашел нужного поля

**Comment by enotniy** [comment]
В мобильной sdk secretKey не используется. Методы executeAsyncOperation и executeSyncOperation работают без ключей. Ошибка 401 вероятно возникает из-за неправильных параметров в [MindboxConfiguration](https://developers.mindbox.ru/docs/sdk-initialization-react-native#1-%D0%B2%D1%8B%D0%B1%D0%BE%D1%80-%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D0%B0-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8-sdk)
